#!/usr/bin/env python3
"""Build a minimal MainActivity stand-in for the live analytics harness.

The harness compiles the *real* MeelanoSql / ManagerAnalytics / MeelanoJalali classes and runs
them against the production Atiran server. Those classes touch exactly six members of
MainActivity (host, port, database, user, password and the stock OUTER APPLY builder), so the
members are copied verbatim out of the real MainActivity instead of being re-implemented: the
harness therefore uses the same credentials and the same generated SQL as the shipped app.

usage: make_stub.py <MainActivity.java> <out/MainActivity.java>
"""
import re
import sys


def grab_const(src, name):
    m = re.search(r"^\s*(?:private |public |protected )*static final [\w\[\]<>, ]+ " + name + r"\s*=\s*[^;]+;", src, re.M)
    if not m:
        raise SystemExit("constant not found: " + name)
    return m.group(0).strip()


def grab_method(src, signature, arity=None):
    idx = src.find(signature)
    if idx < 0:
        raise SystemExit("method not found: " + signature)
    start = src.rfind("\n", 0, idx) + 1
    # walk to the opening brace, then to its match
    i = src.find("{", idx)
    depth = 0
    while i < len(src):
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                return src[start:i + 1]
        i += 1
    raise SystemExit("unbalanced method: " + signature)


def main():
    src_path, out_path = sys.argv[1], sys.argv[2]
    src = open(src_path, encoding="utf-8").read()

    body = []
    for name in ("S_HOST", "S_USER", "S_PASS", "S_DB", "S_KEY"):
        body.append("    " + grab_const(src, name))
    body.append("    static final int SQL_PORT = 1433;")
    body.append("    " + grab_const(src, "ATIRAN_STOCK_OUT_ACTS"))
    body.append("")
    body.append("    " + grab_method(src, "static String hidden(int[] data)"))
    body.append("")
    body.append("    // Same accessors the app uses; the debug overrides of the real class are not needed here.")
    body.append("    static String sqlHost() { return hidden(S_HOST); }")
    body.append("    static int sqlPort() { return SQL_PORT; }")
    body.append("    static String sqlDatabase() { return hidden(S_DB); }")
    body.append("    static String sqlUser() { return hidden(S_USER); }")
    body.append("    static String sqlPassword() { return hidden(S_PASS); }")
    body.append("")
    body.append("    " + grab_method(src, "static String atiranStockApply(String inv, String alias)"))
    body.append("")

    out = ("// GENERATED by tools/analytics-live/make_stub.py from the real MainActivity.java - do not edit.\n"
           "package ir.meelano.android;\n\npublic final class MainActivity {\n"
           + "\n".join(body) + "\n}\n")
    open(out_path, "w", encoding="utf-8").write(out)
    print("stub written:", out_path, len(out), "bytes")


if __name__ == "__main__":
    main()
